---
engines:
  duplication:
    enabled: true
    exclude_paths:
    - test
    config:
      languages:
        javascript:
          mass_threshold: 100 # Defualt: 40
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- gulpfile.js
- textcomplete
